version: '3.8'

services:
  server:
    image: dflx-server
    container_name: dflx-server
    build:
      context: ../
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      PGUSER: dflx
      PGPASSWORD: dflx
      PGDATABASE: maindb
      PGHOST: db
    ports:
      - 3000:3000
    depends_on:
      - db
  db:
    container_name: db
    image: postgres:15.4-alpine3.18
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: dflx
      POSTGRES_PASSWORD: dflx
      POSTGRES_DB: maindb
      PGUSER: dflx
      PGPASSWORD: dflx
      PGDATABASE: maindb
    healthcheck:
      test: pg_isready
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - db_data:/var/lib/postgresql/data:rw
volumes:
  db_data:
