export const BACKGROUND_LAYER_ID = 'BackgroundLayerRect';

export const TRANSFORMER = {
  MIN_SIZE: 5,
  ROTATION_SNAPS: [0, 90, 180, 270],
  ROTATION_ANCHOR_OFFSET: 14,
  PADDING: 6,
  ANCHOR_CORNER_RADIUS: 5,
  ANCHOR_SIZE: 9,
  ANCHOR_STROKE_WIDTH: 1.5,
};

export const RECT = {
  CORNER_RADIUS: 8,
  MIN_SIZE: 5,
};
